version: '3.8'

services:
  # Redis 服务
  redis:
    image: redis:7-alpine
    container_name: hiagent-redis
    ports:
      - "26379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes --maxmemory 512mb --maxmemory-policy allkeys-lru
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

  # API 服务
  api:
    image: luzhipeng728/hiagent-plugin-runtime:latest
    container_name: hiagent-api
    ports:
      - "8500:8000"
    environment:
      - CONFIG=/app/config.yaml
      - SERVICE_TYPE=api
      - PYTHONPATH=/app
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    volumes:
      - ./extensions:/app/extensions
      - ./config.yaml:/app/config.yaml
      - plugin_storage:/tmp/hiagent_storage
      - ./logs:/app/logs
    depends_on:
      - redis
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/ping"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Worker 服务
  worker:
    image: luzhipeng728/hiagent-plugin-runtime:latest
    container_name: hiagent-worker
    environment:
      - CONFIG=/app/config.yaml
      - SERVICE_TYPE=worker
      - PYTHONPATH=/app
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    volumes:
      - ./extensions:/app/extensions
      - ./config.yaml:/app/config.yaml
      - plugin_storage:/tmp/hiagent_storage
      - ./logs:/app/logs
    depends_on:
      - redis
      - api
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "python", "-c", "import redis; redis.Redis(host='redis', port=6379).ping()"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  redis_data:
  plugin_storage: