services:
  redis:
    image: redis:7-alpine
    container_name: hiagent-redis
    # Redis仅内部访问，不暴露端口到宿主机
    # 如需外部访问Redis，可取消注释并修改端口
    # ports:
    #   - "16379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    restart: unless-stopped
    networks:
      - hiagent-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

  api:
    # build: .  # 暂时禁用本地构建
    image: luzhipeng728/hiagent-plugin-runtime:api-latest
    container_name: hiagent-api
    ports:
      - "8000:8000"
    environment:
      - CONFIG=/app/config.yaml
      - SERVICE_TYPE=api
    volumes:
      - ./extensions:/app/extensions
      - ./config.yaml:/app/config.yaml
      - plugin_storage:/tmp/hiagent_storage
    depends_on:
      redis:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - hiagent-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/ping"]
      interval: 30s
      timeout: 10s
      retries: 3

  worker:
    # build: .  # 暂时禁用本地构建
    image: luzhipeng728/hiagent-plugin-runtime:worker-latest
    container_name: hiagent-worker
    environment:
      - CONFIG=/app/config.yaml
      - SERVICE_TYPE=worker
    volumes:
      - ./extensions:/app/extensions
      - ./config.yaml:/app/config.yaml
      - plugin_storage:/tmp/hiagent_storage
    depends_on:
      redis:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - hiagent-network

networks:
  hiagent-network:
    driver: bridge

volumes:
  redis_data:
    driver: local
  plugin_storage:
    driver: local